application: minecraft-ly
version: 20160805-13
runtime: php55
api_version: 1
threadsafe: true
inbound_services:
- warmup

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

# javascripts
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|gif))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|gif))

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: static/\1
  upload: static/(.*\.ttf)
  
- url: /auth/.*
  script: auth/public/index.php
  secure: optional

- url: /
  mime_type: text/html
  static_files: index.html
  upload: index.html
  expiration: "0m"

# angularjs template files
- url: /templates/(.*\.html)
  mime_type: text/html
  static_files: templates/\1
  upload: templates/(.*\.html)
  expiration: "0m"

- url: /.*
  mime_type: text/html
  static_files: index.html
  upload: index.html
  expiration: "0m"
