application: minecraft-ly
version: 1
runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico

- url: /.*
  script: index.php
  secure: optional