application: minecraft-ly
version: 1
runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: favicon\.ico
  
- url: /apple-icon\.png
  static_files: images/apple-icon.png
  upload: apple-icon\.png
  
- url: /apple-icon-precomposed\.png
  static_files: images/apple-icon-precomposed.png
  upload: apple-icon-precomposed\.png

- url: /
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /images
  static_dir: images
  
- url: /templates
  static_dir: templates
  
- url: /auth/.*
  script: auth/public/index.php
  secure: optional
  
- url: /paywithatweet
  script: paywithatweet.php
  secure: optional
  
- url: /.*
  static_files: index.html
  upload: index.html
  